language: scala
scala:
- 2.10.1

jdk:
- openjdk7
- oraclejdk7

env:
- PLAY_VERSION=2.1.1

before_script:
- wget http://downloads.typesafe.com/play/2.1.1/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
-  cd project-code && sbt test

notifications:
email: false
