// Project info

name := "play-appcache"

organization := "com.github.hnakagawa"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.10.0"

// Dependencies

libraryDependencies += "play" %% "play" % "2.1.0"
